### ISSUE TITLE
How to Buy a License?

### ISSUE THREAD

**Issue by Yupjun** [The-OpenROAD-Project/OpenSTA#100]
Hello, I'd like to purchase a license to use the software, where should I contact?
I sent an e-mail to the e-mail address on this website, but the e-mail address seems to have been invalid. Currently, I don't have any contact points on http://www.parallaxsw.com/.

**Comment by jjcherry56** [comment]
Thanks for the heads up, I fixed the email address so it works now.
Please contact James Cherry cherry at parallaxsw dot com
