### ISSUE TITLE
OpenSTA does not update activity data until after report_power has been run; get_property reports stale data.

### ISSUE THREAD

**Issue by taylor-bsg** [The-OpenROAD-Project/OpenSTA#109]
[bug1.txt](https://github.com/The-OpenROAD-Project/OpenSTA/files/9355143/bug1.txt)

**Comment by jjcherry56** [comment]
It was actually somewhat intentional because activity access was put there for debugging. But I see your point so I made it update in 3fb40f9 get_property activity w/o report_power
