### ISSUE TITLE
dockerfile has bugs

### ISSUE THREAD

**Issue by taylor-bsg** [The-OpenROAD-Project/OpenSTA#111]
https://github.com/The-OpenROAD-Project/OpenSTA/blob/12022edc37acf0370f3686eb4ce05c3490b4a7ce/Dockerfile#L29

- Git 224 is no longer available
- make command fails because it does not enter build directory first

Patch below

```
-# Install any git version > 2.6.5
-RUN yum remove -y git* && yum install -y git224
+# Install any git version > 2.6.5 (MBT: I adjusted these rules)
+RUN yum remove -y git* && yum install -y rh-git227
+RUN rm  -f /usr/bin/git; ln -s /opt/rh/rh-git227/root/bin/git /usr/bin/git
+
 
 # Install SWIG
 RUN yum remove -y swig \
@@ -60,7 +62,8 @@ WORKDIR /OpenSTA
 RUN mkdir build
 #RUN cd buld && cmake .. -DCUDD=$HOME/cudd
 RUN cd build && cmake ..
-RUN make -j 8
+RUN cd build && make -j 8





```

**Comment by jjcherry56** [comment]
It would make more sense to file a pull request when you have a patch.
You can test the update; I steer clear of docker.

**Comment by taylor-bsg** [comment]
Thanks! Yeah docker is not my favorite. I will submit pull requests in the future...
