### ISSUE TITLE
Can I specify multiple transition values in the set_input_transitions command?

### ISSUE THREAD

**Issue by avcolgate** [The-OpenROAD-Project/OpenSTA#115]
Hello,
I would like to get a liberty file with a two-dimensional table, but could only get a one-dimensional table, like:
`cell_rise(template_17) {
          values("1.83536,1.84612,1.87492,1.95763,2.21101,3.00188,5.46429");
	}`

How do we use the '-min' and '-max' parameters in the `set_input_transitions` command?

Also there are a lot of the identical templates in the liberty file.
Is there any way to configure this?

**Comment by jjcherry56** [comment]
See examples/example1_typ.lib for a two-dimensional table example.

Use separate set_input_transition commands to set the min/max transition times.
set_input_transition -min .5 {in1 in2}
set_input_transition -max .6 {in1 in2}
