### ISSUE TITLE
specifying clock rise/fall slopes for propagated clocks

### ISSUE THREAD

**Issue by taylor-bsg** [The-OpenROAD-Project/OpenSTA#117]
Is this possible? I checked the docs and did not see any mention of it.

Thanks!

**Comment by jjcherry56** [comment]
Not really. You want the delay calculation for gate delays in the clock network but not the slews? It is a strange request. Seem like you should be using ideal clocks with set_clock_latency and set_clock_transition.

**Comment by taylor-bsg** [comment]
Thanks for your reply. What I mean is, let's say you have a clock tree and you have parasitics for it. The clock tree still has a source, for which we want to specify a slew; what is the mechanism for specifying this?

**Comment by jjcherry56** [comment]
set_input_transition

**Comment by taylor-bsg** [comment]
Actually I am saying, I want it to time the clock tree and everything with
slews etc, but the clock input pin itself has a slew.

**Comment by taylor-bsg** [comment]
Okay great, I did not know this could be applied to a clock signal as well.

M
