### ISSUE TITLE
Can someone explain how to work with 'write_path_spice' command?

### ISSUE THREAD

**Issue by vermut42** [The-OpenROAD-Project/OpenSTA#119]
Can someone explain how to set -path_args? -from/-to keys doesn't working as expected.. or maybe this is my misunderstanding

**Comment by jjcherry56** [comment]
here's an example:
write_path_spice -path_args {-from "in0" -to "out1" -unconstrained} \
  -spice_directory $result_dir \
  -lib_subckt_file "write_spice1.subckt" \
  -model_file "write_spice1.models" \
  -power VDD -ground VSS

Submit a compressed tarfile with a command file and all of the data to run it.
