### ISSUE TITLE
Add report of nets which have not been annotated with SPEF

### ISSUE THREAD

**Issue by tspyrou** [The-OpenROAD-Project/OpenSTA#120]
It is helpful for users to know that their SPEF files are complete and that all nets in the design have parasitics.

**Comment by trcwm** [comment]
Seconded! I have a use case for this right now; the SPEF file loads but the timing of the design doesn't change at all.

**Comment by jjcherry56** [comment]
commit cf4626e adds the report_parasitic_annotation command

**Comment by trcwm** [comment]
Thank you! Much appreciated!
