### ISSUE TITLE
Enhance read_spef to support hierarchical stitching of parasitics

### ISSUE THREAD

**Issue by tspyrou** [The-OpenROAD-Project/OpenSTA#121]
The delete_after_reduce option should be ignored on SPEF annotations which have terminal points on hierarchical nodes until the net is completely annotated and then stitched.
https://github.com/The-OpenROAD-Project/OpenSTA/issues/120 will also be important to ensure all nets and up with complete parasitics.

**Comment by jjcherry56** [comment]
OpenSTA commit 0722453 adds support for hierarchical spef annotation.
