### ISSUE TITLE
OpenSTA.pdf not correctly generated

### ISSUE THREAD

**Issue by rovinski** [The-OpenROAD-Project/OpenSTA#123]
It looks like starting in commit cf4626e `doc/OpenSTA.pdf` is not correctly generated. (`doc/OpenSTA.odt` is still fine)

I see a single, mostly blank page:
![image](https://user-images.githubusercontent.com/3936698/193644739-c2f5d4da-cbd8-4e79-9dc2-cb81bb0ba418.png)

**Comment by jjcherry56** [comment]
I pushed an updated pdf
