### ISSUE TITLE
Command set_power_activity

### ISSUE THREAD

**Issue by kartash02** [The-OpenROAD-Project/OpenSTA#125]
The OpenSTA documentation says that key -activity of the set_power_activity command defines the number of transitions per clock cycle. But in test cases key -activity specifies the transition density. Transition density = activity / clock period. Is it right to use key -activity to set value of transition density instead of activity?

**Comment by jjcherry56** [comment]
Activity is the probability that a pin switches from high to low or low to high in one clock cycle.
I'll update the doc to say this explicitly.
