### ISSUE TITLE
Activity propagation for trigger

### ISSUE THREAD

**Issue by stevvik** [The-OpenROAD-Project/OpenSTA#129]
Hello!

We faced with the issue during activity propagation through trigger pins.
We assume, that in case of frequency on trigger data input pin (D) is greater than on clock pin (CK), the frequency on output pins (Q or QN) must be half of clock pin frequency (Fq=Fck/2). The same must be applicable for activity propagation: activity on output pin must be twice lower than on clock input pin.
But in OpenSTA we see that output pins activities are equal to data input activity!

Simple testcase with single trigger and OpenSTA commands we used is attached.
Top level runfile is  "run_opensta".
[testcase.tgz](https://github.com/The-OpenROAD-Project/OpenSTA/files/10067460/testcase.tgz)

**Comment by jjcherry56** [comment]
You are correct that the D->Q activity propagation should not be greater than the active edge count.
Commit fdba9eb correct this.

I should point out that your testcase is missing a clock definition, which is how the STA knows where the clocks are (NOT the clock pin on the liberty cell).

Also, the units in your set_power_activity commands are incorrect. As the doc explains they are in **transitions per clock cycle**, not transitions per second.

**Comment by stevvik** [comment]
@jjcherry56 ,
I decided to draw you a picture to simplify my explanations (I can send you testcase later if you need):

![OpenSTA_issues](https://user-images.githubusercontent.com/83331683/205331930-296f860d-0bd9-4ab9-96a1-f2c047afbe39.png)

**Comment by stevvik** [comment]
![OpenSTA_issues](https://user-images.githubusercontent.com/83331683/205332951-7b705071-8a58-4a01-a3de-816a34525f2b.png)

**Comment by jjcherry56** [comment]
That is a clock network which has to be defined using create_generated_clock.
