### ISSUE TITLE
documentation improvement request for -min and -max 

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenSTA#131]
in set_input_delay and set_output_delay command documentation:

-max This is the minimum arrival time.
-min This is the maximum arrival time.

and from quartus docs:

-max | Applies value as maximum data required time
-min | Applies value as minimum data required time

It's confusing for me as a beginner.

also would be good to:
 
* state that it's in ns 
* that it's relative to before the edge 
* so a negative number would move it after the edge

**Comment by rovinski** [comment]
> state that it's in ns

It actually is not in ns, it is in the time unit specified by your liberty `.lib` file. sky130 for example is ns, but ASAP7 is ps.

**Comment by jjcherry56** [comment]
The min/max doc is definitely backwards.
ALL commands use the liberty units. I added this to the opening section.
The set_output_delay doc was pretty twisted so I rewrote it. Hopefully it is clearer now.

**Comment by mattvenn** [comment]
thanks for the fast fix on this - appreciated!

**Comment by mattvenn** [comment]
Couple of questions - where is the best place to ask for support for OpenSTA?
I'm trying to learn to read the reports - is there an annotated report somewhere I can study?
