### ISSUE TITLE
incorrect dependencies

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenSTA#136]
In the top level CMakeLists.txt the these dependencies are not correct:
```
if (ZLIB_LIBRARIES)
  target_link_libraries(sta ${ZLIB_LIBRARIES})
endif()

if (CUDD_LIB)
  target_link_libraries(sta ${CUDD_LIB})
endif()
```

OpenSTA should be used, as it is the library with those dependencies, and sta should get them from its dependency on OpenSTA.  This showed up in a recent change I was working on in OR.

**Comment by openroadie** [comment]
Same as OpenROAD#3051
