### ISSUE TITLE
report_power never returns with sky130 clock gates

### ISSUE THREAD

**Issue by gadfort** [The-OpenROAD-Project/OpenSTA#138]
Attached is a testcase where calling `report_power` on a design without clock gates returns file, but with clock gates never returns (as best I can see it seems to be stuck in `ensureActivities()`). @maliberty this is the issue I mentioned the other week, but didn't get around to generating a testcase for till now.
[report_power_loop.tar.gz](https://github.com/The-OpenROAD-Project/OpenSTA/files/10892207/report_power_loop.tar.gz)

To run:
There are two scripts works.tcl and doesntwork.tcl
```
sta -exit work.tcl
# Return with power
sta -exit doesntwork.tcl
# Never finishes 
```

Please let me know if you need anything else from me.

**Comment by jjcherry56** [comment]
fixed by 1e53cc3 issue138 power w/gated clock feedback loops
on https://github.com/jjcherry56/OpenSTA.git
