### ISSUE TITLE
any command to report quality of design

### ISSUE THREAD

**Issue by kunalg123** [The-OpenROAD-Project/OpenSTA#15]
Hi James
Is there any single command (or group of commands) which will give below information? The numbers in the right are just an example from an internal design

Instance count | 229861
worst setup slack(ns) | -42.9503
worst hold slack(ns) | -0.7841
no. of paths analyzed (setup/hold) | 129315
total setup slack(ns) | -1212078.875
total hold slack(ns) | -1902.4175
Design Area(um2) | 9727901
total trans violations(ns) | -52366.2148
total max_cap violations(fF) | -1138.5537

**Comment by jjcherry56** [comment]
rtfm
