### ISSUE TITLE
adding skew to design?

### ISSUE THREAD

**Issue by tristonw109** [The-OpenROAD-Project/OpenSTA#153]
How can skew be added to a design? I have looked through the documentation and can't find a way to add skew. I could be overlooking something. I am a university student doing research with OpenSTA.

**Comment by jjcherry56** [comment]
I don't really know what you mean by "adding skew". If you have ideal clocks (no set_propagated_clock) you can use set_clock_latency to set min/max clock latency to model clock skew before the clock network is inserted.
