### ISSUE TITLE
PBA & GPA

### ISSUE THREAD

**Issue by Ceridli** [The-OpenROAD-Project/OpenSTA#157]
There is a way to improve the accuracy of GPA  without settling for the penalty of PBA.  I am not sure how you are deciding on the slope of an output if there are multiple paths leading to it. If you can center it as the average of multiple candidates,
the maximum error in slope will be reduced by half, and it avoid systematic addition of errors. If you add the delays over a path, relative error will be reduced by 1/sqrt(N), N being the number of stages.  It should reduce total delay error
significantly.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
