### ISSUE TITLE
Interpolation method in OpenSTA

### ISSUE THREAD

**Issue by tamood** [The-OpenROAD-Project/OpenSTA#162]
I am developing an analytics tool around OpenSTA-dumped data. 

For that, I am looking for the code that interpolates NLDM data tables from the liberty, in order to find arc delays and output slews.

Can some maintainer point me towards the place in OpenSTA where these calculations are performed?

**Comment by akashlevy** [comment]
For future reference, the code for delay/slew calculations is pretty much all in the `dcalc/` directory. Specifically, `dcalc/LumpedCapDelayCalc.cc` is where you might want to look.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
