### ISSUE TITLE
About driving resistance and the Arnoldi model order reduction

### ISSUE THREAD

**Issue by gzz2000** [The-OpenROAD-Project/OpenSTA#165]
I know this should be better posted as a discussion. I have a technical question regarding the driving resistance implementation in the reduced order model. 

In OpenSTA, the original R and C matrices are first gone through the Krylov subspace computation. After that, the driving resistance is computed, and added to the top-leftmost element in the reduced order model matrix (the 5x5 matrix H in the [original CT-Arnoldi paper](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=125879195049159137b8f3b7785f4142a089843f)) after multiplied by the [total capacitance](https://github.com/The-OpenROAD-Project/OpenSTA/blob/master/dcalc/ArnoldiDelayCalc.cc#L609). 

This mysteriously works very well and my experiment shows that the only changed element is the top-leftmost element, and it is indeed linearly dependent on the applied driving resistance. I wonder if there is any mathematical reference of this property. Thanks for your help and your elegant open-source Arnoldi implementation!

**Comment by jjcherry56** [comment]
The only documentation of the arnoldi delay calculator implementation is in dcalc/Arnoldi.txt

**Comment by gzz2000** [comment]
Hi James, thanks for pointing me to the documentation. 
Do you know how to contact the original author William Scott? It seems some technical details are not present there and I want to ask if he could kindly give me some hints. Thank you.

**Comment by jjcherry56** [comment]
I do not know how to get in touch with him. If you find anything additional please let me know.
