### ISSUE TITLE
"No paths found" for corners over 8 corners

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenSTA#166]
```
OpenSTA 2.4.0 71a707440d Copyright (c) 2021, Parallax Software, Inc.
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>
```

When defining 8 timing corners, all of them work. But when defining 9, one breaks, and when defining 10, two break, both reporting "No paths found."

[repro.tar.gz](https://github.com/The-OpenROAD-Project/OpenSTA/files/11624324/repro.tar.gz)

**Comment by jjcherry56** [comment]
It has a bit field that overflows with more than 8 corners, so treat that has an unchecked limitation for the time being.

**Comment by jjcherry56** [comment]
fixed in commit https://github.com/parallaxsw/OpenSTA.git
aeb6027 James Cherry 2023-06-01 increase max corner count to 128
