### ISSUE TITLE
Retiming in sta

### ISSUE THREAD

**Issue by Vinayakamk** [The-OpenROAD-Project/OpenSTA#171]
I have tried to set path groups in sta by using group_path cmd. 
How can  I do retiming in opensta.
I tried ' set_retime  - enable'  in SDC file..still I couldn't get. 

If opensta doesn't support retiming,can you suggest a student liable tool

**Comment by jjcherry56** [comment]
gouup_path should automatically trigger a timing update. ser_retime is not an sdc or opensta commmand,
