### ISSUE TITLE
Suggestions to optimize frequency and reduction of gates.

### ISSUE THREAD

**Issue by prajnaputhran17** [The-OpenROAD-Project/OpenSTA#181]
The design I am working on is picorv32
So I basically want to reduce the number of gates in the critical path, how do I do that?

Also could suggest some upsizing or any optimizations with which I can increase the frequency.

**Comment by jjcherry56** [comment]
You run the resizer in openroad to optimize the timing, which uses OpenSTA.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
