### ISSUE TITLE
How will i know the the logics coming across my path of intrest.

### ISSUE THREAD

**Issue by Vinayakamk** [The-OpenROAD-Project/OpenSTA#182]
Hi .I know the path with starting and endpoint..
But I want to know what are all the things ( e.g accumulator,MUX,logic gates) Lying on the path of instrest.
How will i know ? Is there any direct command or other way around

**Comment by akashlevy** [comment]
The `report_checks` command with `-from` and `-to` flags should be allow you to do this. Please see the docs for further details.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
