### ISSUE TITLE
Input slope in delay calculation

### ISSUE THREAD

**Issue by Ceridli** [The-OpenROAD-Project/OpenSTA#185]
I was wondering if there is a description of how it is calculated and used in delay calculation.  Output slope is path dependent and if there are multiple paths through a cell,  output slope will change and impact the delay of the next stage.  My solution to this problem was to track the variation of the driving cell output slope and average it for the use of the next stage, several iterations  of delay calculation stabilizes
the slopes to be used around the center value. This improves accuracy of the total path delay calculation significantly. In addition to the average,
min max range is of interest to me.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
