### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by prathiksha97** [The-OpenROAD-Project/OpenSTA#200]
I am trying to link my design to generate sta reports but then getting an error of core dumped.

![Screenshot from 2023-10-11 09-50-42](https://github.com/The-OpenROAD-Project/OpenSTA/assets/69187224/e0ad6a70-b687-49c9-9869-3d984c0eac79)

**Comment by rovinski** [comment]
Please attach a reproducible for this issue, otherwise it will be extremely difficult to diagnose.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
