### ISSUE TITLE
tcl/Util.tcl proc is_keyword_arg, imprecise support, judge only the first character after "-"

### ISSUE THREAD

**Issue by RichardLCD** [The-OpenROAD-Project/OpenSTA#206]
https://github.com/The-OpenROAD-Project/OpenSTA/blob/3e2295adfd5ffb7053aa6bb68f31b0eae8f2986f/tcl/Util.tcl#L105
It is more rigorous to examine the composition of tcl identifiers, which begin with a letter and an underscore and consist of a letter, a number, and an underscore.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
