### ISSUE TITLE
consider publishing new tagged releases

### ISSUE THREAD

**Issue by proppy** [The-OpenROAD-Project/OpenSTA#208]
I'm trying to get `opensta` packaged for conda-forge and they recommend building from source tarball, see https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos

I'm curious if you've considered publishing tags on this repository and a regular cadence?

I found one tagged release here https://github.com/The-OpenROAD-Project/OpenSTA/releases/tag/v2.2.0 but it looks like there were many changes since then https://github.com/The-OpenROAD-Project/OpenSTA/commits/master/

**Comment by jjcherry56** [comment]
I gave up on bothering with tags a long time ago.
They might be useful when maintaining multiple release branches but I haven't had any reason
to have to deal with that overhead in a long time.
The version (in the cmake file) changes when  there are significant command or api changes.
The git hash is a lot more accurate "version" to indicate what sources someone is using.

**Comment by proppy** [comment]
@hzeller has some automation in place at https://github.com/chipsalliance/verible/releases to tag release periodically, could this be an acceptable solution here?

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
