### ISSUE TITLE
Found might be functionality inconsistency in Search::seedClkArrival with Search::thruClkInfo

### ISSUE THREAD

**Issue by icbenchpeng** [The-OpenROAD-Project/OpenSTA#221]
The inconsistency is about sdc_->isPropagatedClock(pin).

seedClkArrival do always check sdc_->isPropagatedClock if pin clock latency does not exists.
thruClkInfo first check sdc_->isPropagatedClock of the local pin, but then overwrites when pin's clock latency does not exist but hierarchical pin latency thru edge exist. Is there an assumption exist here ?

**Comment by jjcherry56** [comment]
I can't parse your description to understand what your point is. Exactly what assumption are you speculating exists? If you can create a test case that demonstrates a bug I can look into it.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
