### ISSUE TITLE
set_clock_latency constraint affects writing .lib timing models

### ISSUE THREAD

**Issue by mo-hosni** [The-OpenROAD-Project/OpenSTA#223]
`set_clock_latency` does add the clock latency to the hold times of each pin. This should be ignored the same way `set_input_delay` is ignored.

Also, `set_input_transition` affects the hold/setup values for the pins. This is okay as the values are scalar rather than tables as functions of the input transition. However, the tables would be much better so that the input transition constraint won't be used and the model will be more context-independent.

To reproduce: 

[sta-reproducible.partaa.zip](https://github.com/The-OpenROAD-Project/OpenSTA/files/14322993/sta-reproducible.partaa.zip)
[sta-reproducible.partab.zip](https://github.com/The-OpenROAD-Project/OpenSTA/files/14322994/sta-reproducible.partab.zip)
[sta-reproducible.partac.zip](https://github.com/The-OpenROAD-Project/OpenSTA/files/14322996/sta-reproducible.partac.zip)

Comment/Uncomment the clock latency constraint in `./files/home/hosni/caravel_aes_accelerator/openlane/aes_wb_wrapper/signoff.sdc` then run using the script `run.sh`

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
