### ISSUE TITLE
OpenSTA (in ORFS) could not support ccs mem.lib

### ISSUE THREAD

**Issue by diaoerlie** [The-OpenROAD-Project/OpenSTA#225]
hello,

I am trying to run ORFS by make do-floorplan, the flow is crash while reading mem.lib .

1. crash log
[WARNING STA-0125] /local2/OpenROAD-flow-scripts_latest/flow/platforms/*/lib/s*.tt*.lib line 3225, table row has 7 columns but axis has 76.
[WARNING STA-0126] /local2/OpenROAD-flow-scripts_latest/flow/platforms/*/lib/*.tt*lib line 3225, table has 7 rows but axis has 1.
Signal 11 received
Stack trace:
 0# 0x0000000000E08223 in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 1# 0x00007F9E17108F10 in /lib/x86_64-linux-gnu/libc.so.6
 2# sta::LibertyReader::makeTableAxis(int) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 3# 0x000000000116A00D in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 4# sta::makeLibertyComplexAttr(char const*, sta::Vector<sta::LibertyAttrValue*>*, int) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 5# LibertyParse_parse() in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 6# sta::parseLibertyFile(char const*, sta::LibertyGroupVisitor*, sta::Report*) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 7# sta::readLibertyFile(char const*, bool, sta::Network*) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 8# sta::Sta::readLibertyFile(char const*, sta::Corner*, sta::MinMaxAll const*, bool) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
 9# sta::Sta::readLiberty(char const*, sta::Corner*, sta::MinMaxAll const*, bool) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
10# 0x0000000000FFFE70 in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
11# TclNRRunCallbacks in /tools/anaconda3/lib/libtcl8.6.so
12# 0x00007F9E1BCBA19F in /tools/anaconda3/lib/libtcl8.6.so
13# Tcl_EvalEx in /tools/anaconda3/lib/libtcl8.6.so
14# Tcl_Eval in /tools/anaconda3/lib/libtcl8.6.so
15# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
16# ord::tclAppInit(Tcl_Interp*) in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
17# Tcl_MainEx in /tools/anaconda3/lib/libtcl8.6.so
18# main in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
19# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
20# _start in /local2/OpenROAD-flow-scripts_latest/tools/install/OpenROAD/bin/openroad
Command terminated by signal 11

2. mem lib line 3225 is attached:
<img width="974" alt="image" src="https://github.com/The-OpenROAD-Project/OpenSTA/assets/38451771/2de9ea79-8f6e-456e-9c20-39164af3f1f4">

**Comment by jjcherry56** [comment]
I cannot read a screenshot into OpenSTA. Please attach the mem.lib file.
