### ISSUE TITLE
Bug: mark wrong clock pin in findClkPins()

### ISSUE THREAD

**Issue by wuheng01** [The-OpenROAD-Project/OpenSTA#232]
The logic of marking clock pins is to start from the source of clock, then Bfs forward, and mark them in sequence.

For the following logical structure, our opensta will mark `reg2/D` as clock pin. This is actually unreasonable, especially when `reg2/CK` has been driven by other clocks. CLK_BUF2 should be considered as the end of the clock of CLK_A. `CLK_BUF2->BUF_1->reg2/D` should be considered as the data path.
Of course, there is no problem with reg1/CK being recognized as the clock pin.
![image](https://github.com/The-OpenROAD-Project/OpenSTA/assets/64893282/b5cc9fc0-58ff-42d4-840c-9edb9ca34f17)

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
