### ISSUE TITLE
Inconsistent treatment of internal pins as endpoint for "To" and "From"

### ISSUE THREAD

**Issue by smunaut** [The-OpenROAD-Project/OpenSTA#234]
I want to analyze some internal path (starting or ending to internal pins). And generally that works, I get the path analyzed and reported.

However something annoying is that for Starting point a warning gets printed , for instance : 
`Warning: signoff.sdc line 104, 'top_I.branch[28].block[15].um_I.[block_28_15.tt](http://block_28_15.tt/)_um_I/buf_out_uo_out_0/X' is not a valid start point.`

Even though I repeat, it works. That end point will be in the final report and marked as internal endpoint and all is fine.

And the same warning does _not_ get printed for internal destination endpoint, only starting one.

Looking at how they are validated to print that warning, I see that there is : 

* `Sdc::exceptionToInvalid()` in `sdc/Sdc.cc`
* `Sta::exceptionFromInvalid` in `search/Sta.cc`

And the conditions in there are different and I don't really see why internal pins would be considered invalid ...

**Comment by QuantamHD** [comment]
@tspyrou

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
