### ISSUE TITLE
Compilation error - const convert

### ISSUE THREAD

**Issue by aviadb** [The-OpenROAD-Project/OpenSTA#236]
Hello,
I am facing a compilation error with the latest from git

-- STA git sha: 95276f87311b63092b8502832f24f784cc516128
-- System name: Linux
-- Compiler: GNU 14.0.1
-- Build type: RELEASE
-- Build CXX_FLAGS: -O3 -DNDEBUG

```
OpenSTA/dcalc/CcsCeffDelayCalc.cc: In member function ‘virtual sta::ArcDcalcResult sta::CcsCeffDelayCalc::gateDelay(const sta::Pin*, const sta::TimingArc*, const sta::Slew&, float, const sta::Parasitic*, const sta::LoadPinIndexMap&, const sta::DcalcAnalysisPt*)’:
OpenSTA/dcalc/CcsCeffDelayCalc.cc:90:14: error: cannot convert ‘const sta::Slew’ {aka ‘const sta::Delay’} to ‘double’ in assignment
   90 |   in_slew_ = in_slew;
      |              ^~~~~~~
      |              |
      |              const sta::Slew {aka const sta::Delay}
```

**Comment by jjcherry56** [comment]
This is fixed in the official OpenSTA repo https://github.com/parallaxsw/OpenSTA.git by commit
057a5dd2 compile warnings

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
