### ISSUE TITLE
Issue with memory in OpenSTA?

### ISSUE THREAD

**Issue by icesdu** [The-OpenROAD-Project/OpenSTA#241]
Hello, I am a student who is currently studying CCS. Is there any method for learning or development? When I use the latest version of OpenSTA, running projects in the example directory works fine, but when running ccs_sim1.tcl in the test directory, there are issues. Is this normal?
![1717074928055](https://github.com/The-OpenROAD-Project/OpenSTA/assets/119279996/d1ac8bb9-7214-4ce8-8177-e8db9ef0ee44)

**Comment by akashlevy** [comment]
I'm pretty sure CCS support was incomplete in v2.5.0. I believe it is properly supported as of v2.6.0.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
