### ISSUE TITLE
Problem with VCD power analysis

### ISSUE THREAD

**Issue by Lukemagik** [The-OpenROAD-Project/OpenSTA#247]
Good morning, I would like a more detailed description of the power dissipation, and I am trying to estimate the power using .vcd.
The problem is that openSTA is giving me this error:
`Error: snn_lp.vcd line 3584094, unknown variable #405043500`
![image](https://github.com/user-attachments/assets/beff2538-3e0c-4936-b12f-ce1ed697c92f)
And if I look at line 3584094 of the .vcd file, I find:
`$enddefinitions $end`

**Comment by maliberty** [comment]
Issues should be filed at https://github.com/parallaxsw/OpenSTA.  You should include a test case there.
