### ISSUE TITLE
Do you require a CLA to contribute?

### ISSUE THREAD

**Issue by mithro** [The-OpenROAD-Project/OpenSTA#25]
You README.md says;

> OpenSTA is dual licensed. It is released under GPL v3 as OpenSTA and is also licensed for commerical applications by Parallax Software without the GPL's requirements.

For this to be possible you need to require your contributors to [sign a CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) with Parallax Software. However, I don't see anything in your README about this?

You can find out more information about CLAs at https://opensource.google.com/docs/cla/

**Comment by jjcherry56** [comment]
OpenSTA does not support external contributions. I will deal with CLAs if/when that is necessary.
