### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by egiacomin** [The-OpenROAD-Project/OpenSTA#29]
Hello,
I am trying to install OpenSTA in "standalone" mode. I wanted to use cmake, but the link provided in the "Installing with CMake" subsection is dead:

-----------
$ git clone https://xp-dev.com/git/opensta
Cloning into 'opensta'...
fatal: repository 'https://xp-dev.com/git/opensta/' not found
-----------

**Comment by jjcherry56** [comment]
I guess using the one you found the README.md file in wasn't obvious enough for you.
I updated it to the github url.

**Comment by egiacomin** [comment]
Just reporting a typo that's all :)
