### ISSUE TITLE
How can I find the class definition of Instance & Pin?

### ISSUE THREAD

**Issue by SimLogic** [The-OpenROAD-Project/OpenSTA#35]
Hello, James,
   Like below source API shows, could you please point me to the source code of class like Pin or Instance?

   Thanks!

Pin *
Network::findPin(const Instance *instance,
		 const LibertyPort *port) const
{
  return findPin(instance, port->name());
}

**Comment by jjcherry56** [comment]
They don't exist. See doc/StaApi.txt
