### ISSUE TITLE
Support for hierarchical sdf annotation

### ISSUE THREAD

**Issue by andyfox-rushc** [The-OpenROAD-Project/OpenSTA#37]
Annotating sdf with -path seems not to work for hierarchical design. Issue seems to be in stringPrint in findPin in SdfReader. Possible fix shown below. Test case (hier.tar.gz) showing problem attached -- run without fix yields missing pin error messages, run with fix seems ok
[hier_sdf.tar.gz](https://github.com/The-OpenROAD-Project/OpenSTA/files/4067683/hier_sdf.tar.gz)
.

Pin *
SdfReader::findPin(const char *name)
{
  if (path_) {
    string path_name;
    // original code, path name not used..
    //   stringPrint(path_name, path_, divider_, name);
    //AF: Bug fix: include path hierarchy in name..
       stringPrint(path_name, "%s%c%s",path_, divider_, name);
    Pin *pin = network_->findPin(path_name.c_str());
    return pin;
  }
  else
    return network_->findPin(name);
}

**Comment by jjcherry56** [comment]
thanks for the concise test case.
fixed in commit 679b5d7
