### ISSUE TITLE
The cudd dependency is a dead package

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenSTA#41]
Host for ftp://vlsi.colorado.edu/pub/ doesn't resolve.

**Comment by yurivict** [comment]
It moved to https://davidkebo.com/cudd

**Comment by jjcherry56** [comment]
By the default build doesn't use cudd.
README.md references https://sourceforge.net/projects/cudd-mirror and https://davidkebo.com/cudd, not ftp://vlsi.colorado.edu/pub so I don't know how you got there

**Comment by yurivict** [comment]
> By the default build doesn't use cudd.

It links to ```cudd``` by default when it is installed. cmake finds it.

**Comment by Visruat** [comment]
is CUDD a compulsory dependency for OpenSTA
