### ISSUE TITLE
Please consider moving headers into a subdirectory

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenSTA#42]
The project installs 164 files into /usr/local/include. It's better if they would go into a dedicated subdirectory, for example /usr/local/include/opensta. Fewer files would be in include/, and the possibility of conflicts with other packages would also be lower.

**Comment by jjcherry56** [comment]
good idea. nobody really uses make install, but that makes sense.
I'm convinced the library or headers even belong in the install target.
950b7c3 master origin/master mv install headers in /opensta, missing headers

**Comment by yurivict** [comment]
> nobody really uses make install

The Arch Linux packages uses ```make install```: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opensta-git

The FreeBSD package also uses ```make install```.

I'm sure all other packages too: https://repology.org/project/opensta/versions

**Comment by jjcherry56** [comment]
I mean actual code users, not generic package installers.
20 years of users pre-github and I doubt they ever used make install.

**Comment by yurivict** [comment]
Yes, users are supposed to install software through packages these days, and packages use ```make install```.
