### ISSUE TITLE
Could you please make a release and assign some version number?

### ISSUE THREAD

**Issue by yurivict** [The-OpenROAD-Project/OpenSTA#55]
Several systems have ports for OpenSTA: https://repology.org/project/opensta/versions, but port maintainers have to make up version numbers because here on GitHub no version number is assigned.

Could you please make a release and assign a version number so that people can track changes in the project?

Thank you.
Yuri

**Comment by jjcherry56** [comment]
I have no idea why you or anyone else is publishing ports for OpenSTA or how to support them really. OpenSTA is on github as part of OpenROAD, which itself is early in development and not really in a position to support outside users at this point. I think made a github "release" but it is not something I consider at all important.
