### ISSUE TITLE
Support with insert_buffer

### ISSUE THREAD

**Issue by nickson-jose** [The-OpenROAD-Project/OpenSTA#57]
Relatively new to OpenSTA
I want to insert a buffer between net _03412_ and load pin _33464_/A2 as shown in below timing report snippet:

```
    Fanout     Cap    Slew   Delay    Time   Description
-----------------------------------------------------------------------------
                          0.13    0.12    1.28 ^ _33458_/X (sky130_fd_sc_hd__buf_1)

 4             0.01                                     _03412_ (net)
                           0.13    0.00    1.28 ^ _33464_/A2 (sky130_fd_sc_hd__a21o_4)
                           0.01    0.08    1.36 ^ _33464_/X (sky130_fd_sc_hd__a21o_4)

```

Tried:

```
% help insert_buffer 
insert_buffer buffer_name buffer_cell net load_pins buffer_out_net_name
% 
% insert_buffer _my_buf_ sky130_fd_sc_hd__buf_4  _03412_  _33464_/A2  _my_net_
invalid command name "insert_buffer_cmd"

```
Can't really figure out where I'm going wrong. Also couldn't find any reference in the openSTA manual for this command. Any help is appreciated

**Comment by jjcherry56** [comment]
You aren't doing anything wrong. I removed the command but left the tcl proc behind.
154dcf00 James Cherry Fri Jun 14 16:52:34 2019 -0700 rm insert_buffer
Use the make_instance/make_net/disconnect_pin/connect_pin primitives which are maybe less convenient but 
more flexible.
