### ISSUE TITLE
support for tclreadline

### ISSUE THREAD

**Issue by bfg86** [The-OpenROAD-Project/OpenSTA#59]
Hi,
It would be nice to have support for command history using up/down keys. 
I have a patch available, basically a copy of what's done in the OpenROAD repository ([issue 136](https://github.com/The-OpenROAD-Project/OpenROAD/issues/136)). Let me know if I should open a pull request.

**Comment by mbalestrini** [comment]
I second this. Having history and the possibility to use the left and right keys to modify something would be a great feature.

**Comment by bfg86** [comment]
@jjcherry56 added support for tclreadline in [15d9333](https://github.com/The-OpenROAD-Project/OpenSTA/commit/15d93339f998da0daf8aea6f05e1cec56114336c).
