### ISSUE TITLE
compile errors from missing declarations

### ISSUE THREAD

**Issue by AppMathIsRealMath** [The-OpenROAD-Project/OpenSTA#65]
I've recently started getting compile errors about missing declarations:

OpenSTA/search/Sim.cc:62:5: error: ‘internalErrorNoThrow’ was not declared in this scope
   62 |     internalErrorNoThrow("non-zero cudd reference counts");

internalError and internalErrorNoThrow don't seem to be defined anywhere in OpenSTA. These functions are used in:

./search/Sim.cc:    internalErrorNoThrow("non-zero cudd reference counts");
./search/Sim.cc:    internalError("unknown function operator");
./graph/DelayNormal2.cc:      internalError("unknown early/late value.");
./graph/DelayNormal1.cc:      internalError("unknown early/late value.");

**Comment by jjcherry56** [comment]
only with CUDD or SSTA conditional compilation
fixed in 14bacb30 cudd/ssta compile errors
