### ISSUE TITLE
another compile error from missing declarations

### ISSUE THREAD

**Issue by AppMathIsRealMath** [The-OpenROAD-Project/OpenSTA#69]
Probably a similar problem to #65 while building with cudd:

OpenSTA/search/Sim.cc:69:3: error: ‘debugPrint2’ was not declared in this scope; did you mean ‘debugPrint’?
   69 |   debugPrint2(debug_, "sim", 4, "find sense pin %s %s",
      |   ^~~~~~~~~~~
      |   debugPrint
OpenSTA/search/Sim.cc:95:3: error: ‘debugPrint1’ was not declared in this scope; did you mean ‘debugPrint’?
   95 |   debugPrint1(debug_, "sim", 4, " %s", timingSenseString(sense));
      |   ^~~~~~~~~~~
      |   debugPrint

**Comment by jjcherry56** [comment]
fixed in 0348fcfa cudd compile errors
