### ISSUE TITLE
cmd issue

### ISSUE THREAD

**Issue by 1347806** [The-OpenROAD-Project/OpenSTA#70]
Hi!  thanks to the developers of this software. I am a freash man about OpenSTA.
I follow the manual and run the example1.tcl successfully，but when I used cmd like  **all_clocks** or **all_register** the tools report like this
`% all_clocks`
`_400ac1dfff7f0000_p_Clock`

`% all_register`
`_d095c0dfff7f0000_p_Instance _5099c0dfff7f0000_p_Instance _e0a0c0dfff7f0000_p_Instance`
I check the example1.tcl and find
`create_clock -name clk -period 10 {clk1 clk2 clk3}`
the design has 3 clocks：clk1 clk2 and clk3.
Can OpenSTA report as normal name of objects like clock or register when use cmd like all_clocks or all_register？
Do I need to install other prerequisites to achieve this function？？

**Comment by jjcherry56** [comment]
get_name
