### ISSUE TITLE
Why load_slew in LumpedCapDelayCalc::loadDelay is scaled by multi_drvr_slew_factor_ twice?

### ISSUE THREAD

**Issue by bravo-t** [The-OpenROAD-Project/OpenSTA#71]
Hi James,

I'm a fan of the OpenSTA project. Recently I have been studying the code and I found something I cannot understand. As mentioned in the title, the value of load_slew multiplied by multi_drvr_slew_factor_ twice, one before thresholdAdjust, one after:

https://github.com/The-OpenROAD-Project/OpenSTA/blob/045b7a7c198fdb88941a2f554ff7649e34d8f5d0/dcalc/LumpedCapDelayCalc.cc#L188
https://github.com/The-OpenROAD-Project/OpenSTA/blob/045b7a7c198fdb88941a2f554ff7649e34d8f5d0/dcalc/LumpedCapDelayCalc.cc#L191

I think scale the slew value once is enough, is this code a duplicate multiplication, or am I missing anything? Thanks for the answer. 

Regards, 
Bin

**Comment by jjcherry56** [comment]
You are correct, it is wrong. Fixed by
72d1df9e  LumpedCapDelayCalc::loadDelay multi_driver derate once
