### ISSUE TITLE
return all paths from/to a pin

### ISSUE THREAD

**Issue by ch-oak** [The-OpenROAD-Project/OpenSTA#73]
Hi, thanks for your work!

Is it possible to return all paths from or to a pin using certain setting? For example, in your example1 case:
% find_timing_paths -unique_paths_to_endpoint -to [list [get_pins "r3/D"]]
return "r2/Q->u1/A->u1/Z->u2/A2->u2/ZN->r3/D", not return "r1/Q->u2/A1->u2/ZN->r3/D"

Please ignore, seem "-endpoint_count 100" works.

**Comment by HumzaSami00** [comment]
Hi @ch-oak , Did you able to find the solution? I also want to find critical path in design.
