### ISSUE TITLE
report_power does not return anything.

### ISSUE THREAD

**Issue by subhajit26** [The-OpenROAD-Project/OpenSTA#74]
Hi, 
         I am trying to use opensta for power analysis but after setting it up when i run the report_power command it is not returning the power . I am getting the property such fullname or others but this command does not seem to work. Please let me know is there any work around for the power calculation analysis. Also please let me know is there any way to get the area of the a particular cell or instance from opensta.

**Comment by jjcherry56** [comment]
I cannot help you without a test case.
There is no accessor for area in opensta. OpenRoad has a report_design_area command.
