### ISSUE TITLE
Even after reading .spef file report_annotated_check shows all are 

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenSTA#76]
We are using the exampl4.tcl
############### example4.tcl###################
# delay calc example with parasitics
read_liberty example1_slow.lib
read_verilog example1.v
link_design top
read_spef example1.dspef
create_clock -name clk -period 10 {clk1 clk2 clk3}
set_input_delay -clock clk 0 {in1 in2}
report_checks
###############################################

Even with .dspef reading, report_annotated check shows, nothing is annotated ? Do we need to add additional command here ?

<pre>% report_annotated_check
                                                            Not   
Check type                        Total    Annotated   Annotated
----------------------------------------------------------------
cell setup arcs                       3           0           3
cell hold arcs                        3           0           3
----------------------------------------------------------------
                                      6           0           6
</pre>

**Comment by jjcherry56** [comment]
report_annotated_check reports unannotated SDF, not SPEF, and only timing checks, not timing delays.
