### ISSUE TITLE
OpenSTA: Add support for internal_power group that doesn't distinguishe between rise_power and fall_power

### ISSUE THREAD

**Issue by beejan** [The-OpenROAD-Project/OpenSTA#84]
Currently if a power group doesn't define rise_ and fall_power and specifies only power () {} block, it is not handled correctly.  An example is as shown below and is shown in the Liberty user guide as well.

               internal_power () {
                        when            : "!E & !GCK & !SE";
                        power(Hidden_Power_clock) {
                                values ("0.002941,0.002880,0.002933,0.003171,0.003652,0.004888,0.007639");
                        }
                }

Thanks,
Ali Sadigh

**Comment by jjcherry56** [comment]
supported by opensta commit 8bcb0eb liberty internal_power power group for rise/fall
